dependencies:
  # - <organisation/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.3.3
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2
  - curiousdweller/safe-contracts@1.3.0
  - curiousdweller/v2-periphery@1.2.1
  - Uniswap/v2-core@1.0.1

compiler:
  solc:
    optimizer:
      enabled: true
      runs: 800
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3'
      - '@gnosis=curiousdweller/safe-contracts@1.3.0'
      - '@zeppelinupgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2'
      - '@uniperiphery=curiousdweller/v2-periphery@1.2.1'
      - '@uniswap=Uniswap/v2-core@1.0.1'
    

networks:
  development:
    cmd_settings:
      default_balance: 100000
  